title: Scary spot the difference
hero_image: images/banner.png
description: Make a scary 'spot the difference' game in Python
listed: false
copyedit: false
last_tested: "2026-01-23"
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
- title: Step 7
- title: Step 8
- title: Step 9
  completion:
  - internal
  - external
