title: Scary spot the difference
hero_image: images/banner.png
description: Make a scary 'spot the difference' game in Python
listed: false
copyedit: false
last_tested: "2026-01-23"
landing: true
steps:
  - title: Show the difference image
  - title: Swap to a scary image
    completion:
      - engaged
  - title: Make it random
    completion:
      - internal
  - title: Change the range
    completion:
      - external
